<?php

namespace Database\Seeders;

use App\Models\Character;
use Illuminate\Database\Seeder;

final class CharacterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $characters = [
            [
                'slug' => 'aron',
                'name' => 'Aron',
                'title' => 'The Self-Proclaimed Hero',
                'archetype' => 'Boxer Delusional',
                'weapon' => 'Sarung Tinju & Disiplin Otodidak',
                'premise' => 'Pemuda berkacamata yang sangat menggemari anime laga dan mendedikasikan hidupnya melatih teknik tinju secara disiplin. Ia mengalami delusi akut dan meyakini dirinya adalah protagonis utama (main character) dari takdir dunia ini.',
                'obstacle' => 'Ia selalu dicemooh, dirundung, dan dianggap sosok aneh yang terperangkap dalam delusinya sendiri. Tak seorang pun mengakui hasil latihannya.',
                'ambition' => 'Takhta Fallen menjadi satu-satunya panggung absolut baginya untuk memvalidasi martabatnya bahwa ia adalah pahlawan nyata, bukan sekadar figuran.',
                'quote' => 'Dunia ini cuma naskah, dan takhta itu panggung tempat gue ngebuktiin siapa pemeran utamanya!',
                'image_path' => 'assets/characters/aron.jpeg',
                'combat_tags' => ['Rushdown', 'Jab-Cross Combos', 'Wall Slide & Jump'],
                'power' => 3,
                'speed' => 5,
                'range' => 2,
                'difficulty' => 2,
                'display_order' => 1,
            ],
            [
                'slug' => 'mike',
                'name' => 'Mike',
                'title' => 'The Enraged Senior',
                'archetype' => 'Brawler',
                'weapon' => 'Kursi Lipat Besi Kampus',
                'premise' => 'Mahasiswa tingkat akhir berwajah kuyu yang siap menuntaskan sidang skripsi, namun ruang ujiannya luluh lantak akibat pertempuran liar perebutan Fallen. Terbakar amarah, ia membawa kursi lipat besi kampus sebagai senjata pembalasan.',
                'obstacle' => 'Penundaan sidang memaksanya membayar UKT semester baru, menghadapi ancaman drop out, serta beban tuntutan keluarga yang menumpuk.',
                'ambition' => 'Menguasai Fallen adalah jalan pintas baginya untuk menghentikan kekacauan birokrasi, mengamankan ijazah, dan memaksakan kelulusannya sendiri tanpa revisi.',
                'quote' => 'Gue nggak peduli takhta magis lo semua! Ruang sidang gue hancur, UKT gue jalan terus, dan kepala lo bakal ngerasain kursi lipat ini!',
                'image_path' => 'assets/characters/mike.jpeg',
                'combat_tags' => ['Heavy Impact', 'Armored Smash', 'Chair Slam & Knockback'],
                'power' => 5,
                'speed' => 2,
                'range' => 3,
                'difficulty' => 2,
                'display_order' => 2,
            ],
            [
                'slug' => 'kemet',
                'name' => 'Kemet',
                'title' => 'The Defective Predator',
                'archetype' => 'Berserker Mutan',
                'weapon' => 'Mutasi Cakar Logam Biologis',
                'premise' => 'Pemuda berpenampilan lusuh yang merupakan subjek uji laboratorium rekayasa genetika. Dicap sebagai produk cacat, ia memanifestasikan mutasi cakar logam biologis di kedua punggung tangannya.',
                'obstacle' => 'Dibuang dan diburu oleh laboratorium penciptanya serta dikucilkan masyarakat sipil sebagai monster buas tanpa tempat berlindung.',
                'ambition' => 'Bertekad merebut takhta untuk membalik hierarki dan membuktikan mutan cacat mampu menundukkan serta meremukkan arogansi dunia.',
                'quote' => 'Mereka ciptain gue buat jadi senjata, tapi buang gue karena dianggap cacat. Takhta ini bakal buktiin siapa mangsa dan siapa pemangsanya.',
                'image_path' => 'assets/characters/kemet.jpeg',
                'combat_tags' => ['Thrust Combos', 'Feral Agility', 'Rising Slashes'],
                'power' => 4,
                'speed' => 4,
                'range' => 2,
                'difficulty' => 3,
                'display_order' => 3,
            ],
            [
                'slug' => 'om-hami',
                'name' => 'Om Hami',
                'title' => 'The Local Peacekeeper',
                'archetype' => 'Enforcer Warga',
                'weapon' => 'Sandal Jepit & Tongkat Kayu Pos Ronda',
                'premise' => 'Pria paruh baya bersandal jepit yang awalnya hanya nongkrong di posko sambil merokok. Ia terseret ke arena karena menganggap turnamen Fallen hanyalah ulah pemuda pembuat onar yang mengusik ketenteraman wilayahnya.',
                'obstacle' => 'Pertempuran Fallen merusak lapak dagang warga dan merampas ketenteraman lingkungannya yang tenang.',
                'ambition' => 'Tanpa kepedulian pada mitos takhta pengabul hajat, Om Hami turun membawa tongkat kayu demi menertibkan para petarung dan mengembalikan kedamaian pos ronda.',
                'quote' => 'Kalian bocah-bocah pada ribut apa sih di sini?! Warung kopi hancur, pos ronda ambruk! Pulang sekarang atau saya sabet pakai tongkat ronda!',
                'image_path' => 'assets/characters/om_hami.jpeg',
                'combat_tags' => ['Crowd Control', 'Stun Knockback', 'Zone Defense'],
                'power' => 4,
                'speed' => 2,
                'range' => 3,
                'difficulty' => 1,
                'display_order' => 4,
            ],
            [
                'slug' => 'muslan',
                'name' => 'Muslan',
                'title' => 'The Southern Troubadour',
                'archetype' => 'Troubadour Indie',
                'weapon' => 'Hardcase Gitar Akustik & Resonansi Nada',
                'premise' => 'Gitaris indie asal wilayah selatan dengan gaya berpakaian santai dan sandal jepit. Ia membawa hardcase gitar ikonik di punggungnya dan memandang arena sayembara pertarungan sebagai panggung terbesarnya.',
                'obstacle' => 'Industri musik komersil terus menolak karya-karyanya hingga modal tabungannya terkuras habis tanpa sisa.',
                'ambition' => 'Terjebak dalam rasa putus asa akibat lagunya tak pernah didengar, ia nekat mengejar takhta pengabul hajat agar seluruh dunia serentak mendengarkan musiknya.',
                'quote' => 'Label rekaman boleh nolak demo gue, tapi di arena ini distorsi gitar gue bakal bikin telinga kalian tunduk.',
                'image_path' => 'assets/characters/muslan.jpeg',
                'combat_tags' => ['Mid-Range Sweep', 'Sonic Disruption', 'Rhythm Counter'],
                'power' => 3,
                'speed' => 3,
                'range' => 4,
                'difficulty' => 3,
                'display_order' => 5,
            ],
            [
                'slug' => 'butler',
                'name' => 'Butler',
                'title' => 'The Disgraced Mixologist',
                'archetype' => 'Duelist Eks-Bartender',
                'weapon' => 'Serbet Pusaka Berenergi Api Magis',
                'premise' => 'Pelayan berpenampilan rapi dengan rompi formal yang dipecat sepihak dari pekerjaannya. Ia mengandalkan kain serbet pusaka berenergi api magis untuk bertarung di arena dengan teknik yang anggun namun mematikan.',
                'obstacle' => 'Kemiskinan ekstrem dan status sosial rendah membuatnya terancam terusir dari kontrakan serta kelaparan tanpa pesangon sepeser pun.',
                'ambition' => 'Duduk di takhta Fallen adalah pertaruhan hidup-matinya untuk menghapus nasib melarat selamanya dan mendirikan tempat kehormatannya sendiri.',
                'quote' => 'Pelayanan yang sempurna membutuhkan ketepatan dan panas yang pas. Serbet ini siap menyajikan kekalahan terhormat untuk Anda.',
                'image_path' => 'assets/characters/butler.jpeg',
                'combat_tags' => ['Flame Traps', 'Precision Thrust', 'Graceful Parry'],
                'power' => 4,
                'speed' => 3,
                'range' => 3,
                'difficulty' => 4,
                'display_order' => 6,
            ],
            [
                'slug' => 'rin',
                'name' => 'Rin',
                'title' => 'The Mystic Weaver',
                'archetype' => 'Zoner Pewaris',
                'weapon' => 'Selendang Sutra Kosmik Leluhur',
                'premise' => 'Gadis berhijab yang mewarisi selendang sutra ajaib bernuansa kosmik di rumah peninggalan neneknya. Kain tersebut mampu bergerak dinamis menjadi cambuk, pelindung, dan senjata jarak menengah.',
                'obstacle' => 'Terkekang oleh budaya patriarki dan pandangan sempit masyarakat bahwa wanita harus bersikap pasif dan tunduk.',
                'ambition' => 'Rin memasuki medan laga Fallen untuk menghancurkan stereotip tersebut dan membuktikan martabat serta kepemimpinan kaumnya di puncak dunia.',
                'quote' => 'Jangan pernah mengira kelembutan sutra ini tak mampu menghempaskanmu ke dasar jurang. Takhta ini milik mereka yang berjiwa tangguh.',
                'image_path' => 'assets/characters/rin.jpeg',
                'combat_tags' => ['Long Range Whip', 'Barrier Weave', 'Space Denial'],
                'power' => 3,
                'speed' => 4,
                'range' => 5,
                'difficulty' => 4,
                'display_order' => 7,
            ],
            [
                'slug' => 'sunkibo',
                'name' => 'Sunkibo',
                'title' => 'The Ignored Scion',
                'archetype' => 'Trickster Mitologi',
                'weapon' => 'Tongkat Pusaka Emas & Mahkota Sakti',
                'premise' => 'Pemuda berekor kera dan berkacamata yang membawa darah langsung dari Raja Kera mitologi. Dilengkapi tongkat pusaka berukir emas dan mahkota sakti, ia bergerak sangat lincah di arena pertempuran.',
                'obstacle' => 'Kerap diabaikan dan dianggap remeh oleh para dewa kahyangan yang selalu membandingkannya dengan reputasi sang kakek buyut.',
                'ambition' => 'Didorong rasa bosan dan haus pengakuan, ia sengaja membajak turnamen mortal di bumi agar para dewa langit menoleh dan mengakui kehebatannya.',
                'quote' => 'Kakek gue boleh ngacak-ngacak kahyangan ratusan tahun lalu, tapi hari ini, gue yang bakal bikin seluruh dunia nggak bisa ngalihin pandangan!',
                'image_path' => 'assets/characters/sunkibo.png',
                'combat_tags' => ['Acrobatic Feint', 'Staff Vault', 'Trick Combos'],
                'power' => 4,
                'speed' => 5,
                'range' => 4,
                'difficulty' => 5,
                'display_order' => 8,
            ],
        ];

        foreach ($characters as $data) {
            Character::updateOrCreate(
                ['slug' => $data['slug']],
                $data
            );
        }
    }
}
